# Session
server:
  session:
    timeout: 3600
    cookie:
      http-only: true

# Actuator
management:
  context-path: /admin
  security:
    enabled: false

security:
  basic:
    enabled: false

info:
  application:
    env: Development

# Logging
logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.security: INFO
    org.hibernate: WARN
    org.thymeleaf: WARN